name: create_and_publish_docker_images

on : 
  workflow_call:
    inputs:
      image_name: 
        required: true
        type: string
      tag: 
        required: true
        type: string 
    
    secrets: 
      registry_username: 
        required: true
      registry_password:
        required: true

jobs:
  build: 
    runs-on : ubuntu-18.04
    # ${{"matrix.os"}}
    # strategy:
    #   matrix: 
    #     os: ["ubuntu-latest","mac-os"]

    steps:
      - uses: actions/checkout@v2

      - name: setup BuildBox
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1

        with:
          username: ${{secrets.registry_username}}
          password: ${{secrets.registry_password}}

      - name: Set the tag
        run: | 
          if [-z "${{inputs.tag}}"]
          then 
            echo "final_tag=latest" >>$GITHUB_ENV
          else 
            echo "final_tag=${{inputs.tag}}" >> >$GITHUB_ENV
          fi 
      - name : Build and Push the image 
        uses: docker/build-push-action@v2 
        with : 
          context : .
          push: true
          tags : ${{secrets.registry_username}}/${{inputs.image_name}}:${{env.final_tag}}



  